const INITIAL_STATE = {
    produtos: [
        {nome: "Produto 1", id: Math.random(), preco: 555, quantidade: 3, descricao: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc tellus augue, imperdiet vitae risus in, laoreet efficitur neque. Integer finibus convallis metus, non feugiat lorem posuere a.", noCarrinho: 5, emProcessoDePagamento: 5, NosPedidos: 5, status: "Em Produção"},
        {nome: "Produto 2", id: Math.random(), preco: 3, quantidade: 5, descricao: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc tellus augue, imperdiet vitae risus in, laoreet efficitur neque. Integer finibus convallis metus, non feugiat lorem posuere a.", noCarrinho: 5, emProcessoDePagamento: 5, NosPedidos: 5, status: "Em Produção"},
        {nome: "Produto 3", id: Math.random(), preco: 4, quantidade: 4, descricao: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc tellus augue, imperdiet vitae risus in, laoreet efficitur neque. Integer finibus convallis metus, non feugiat lorem posuere a.", noCarrinho: 5, emProcessoDePagamento: 5, NosPedidos: 5, status: "Em Produção"},
        {nome: "Produto 4", id: Math.random(), preco: 5, quantidade: 3, descricao: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc tellus augue, imperdiet vitae risus in, laoreet efficitur neque. Integer finibus convallis metus, non feugiat lorem posuere a.", noCarrinho: 5, emProcessoDePagamento: 5, NosPedidos: 5, status: "Em Produção"},
        {nome: "Produto 5", id: Math.random(), preco: 3, quantidade: 5, descricao: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc tellus augue, imperdiet vitae risus in, laoreet efficitur neque. Integer finibus convallis metus, non feugiat lorem posuere a.", noCarrinho: 5, emProcessoDePagamento: 5, NosPedidos: 5, status: "Em Produção"},
        {nome: "Produto 6", id: Math.random(), preco: 4, quantidade: 4, descricao: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc tellus augue, imperdiet vitae risus in, laoreet efficitur neque. Integer finibus convallis metus, non feugiat lorem posuere a.", noCarrinho: 5, emProcessoDePagamento: 5, NosPedidos: 5, status: "Em Produção"},
        {nome: "Produto 7", id: Math.random(), preco: 5, quantidade: 3, descricao: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc tellus augue, imperdiet vitae risus in, laoreet efficitur neque. Integer finibus convallis metus, non feugiat lorem posuere a.", noCarrinho: 5, emProcessoDePagamento: 5, NosPedidos: 5, status: "Em Produção"},
        {nome: "Produto 8", id: Math.random(), preco: 3, quantidade: 5, descricao: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc tellus augue, imperdiet vitae risus in, laoreet efficitur neque. Integer finibus convallis metus, non feugiat lorem posuere a.", noCarrinho: 5, emProcessoDePagamento: 5, NosPedidos: 5, status: "Em Produção"},
        {nome: "Produto 9", id: Math.random(), preco: 4, quantidade: 4, descricao: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc tellus augue, imperdiet vitae risus in, laoreet efficitur neque. Integer finibus convallis metus, non feugiat lorem posuere a.", noCarrinho: 5, emProcessoDePagamento: 5, NosPedidos: 5, status: "Em Produção"},
        {nome: "Produto 10", id: Math.random(), preco: 5, quantidade: 3, descricao: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc tellus augue, imperdiet vitae risus in, laoreet efficitur neque. Integer finibus convallis metus, non feugiat lorem posuere a.", noCarrinho: 5, emProcessoDePagamento: 5, NosPedidos: 5, status: "Em Produção"},
        {nome: "Produto 12", id: Math.random(), preco: 3, quantidade: 5, descricao: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc tellus augue, imperdiet vitae risus in, laoreet efficitur neque. Integer finibus convallis metus, non feugiat lorem posuere a.", noCarrinho: 5, emProcessoDePagamento: 5, NosPedidos: 5, status: "Em Produção"},
        {nome: "Produto 13", id: Math.random(), preco: 4, quantidade: 4, descricao: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc tellus augue, imperdiet vitae risus in, laoreet efficitur neque. Integer finibus convallis metus, non feugiat lorem posuere a.", noCarrinho: 5, emProcessoDePagamento: 5, NosPedidos: 5, status: "Em Produção"},
        {nome: "Produto 14", id: Math.random(), preco: 5, quantidade: 3, descricao: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc tellus augue, imperdiet vitae risus in, laoreet efficitur neque. Integer finibus convallis metus, non feugiat lorem posuere a.", noCarrinho: 5, emProcessoDePagamento: 5, NosPedidos: 5, status: "Em Produção"},
        {nome: "Produto 15", id: Math.random(), preco: 3, quantidade: 5, descricao: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc tellus augue, imperdiet vitae risus in, laoreet efficitur neque. Integer finibus convallis metus, non feugiat lorem posuere a.", noCarrinho: 5, emProcessoDePagamento: 5, NosPedidos: 5, status: "Em Produção"},
        {nome: "Produto 16", id: Math.random(), preco: 4, quantidade: 4, descricao: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc tellus augue, imperdiet vitae risus in, laoreet efficitur neque. Integer finibus convallis metus, non feugiat lorem posuere a.", noCarrinho: 5, emProcessoDePagamento: 5, NosPedidos: 5, status: "Em Produção"},
        {nome: "Produto 17", id: Math.random(), preco: 5, quantidade: 3, descricao: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc tellus augue, imperdiet vitae risus in, laoreet efficitur neque. Integer finibus convallis metus, non feugiat lorem posuere a.", noCarrinho: 5, emProcessoDePagamento: 5, NosPedidos: 5, status: "Em Produção"},
        {nome: "Produto 18", id: Math.random(), preco: 3, quantidade: 5, descricao: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc tellus augue, imperdiet vitae risus in, laoreet efficitur neque. Integer finibus convallis metus, non feugiat lorem posuere a.", noCarrinho: 5, emProcessoDePagamento: 5, NosPedidos: 5, status: "Em Produção"},
        {nome: "Produto 19", id: Math.random(), preco: 4, quantidade: 4, descricao: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc tellus augue, imperdiet vitae risus in, laoreet efficitur neque. Integer finibus convallis metus, non feugiat lorem posuere a.", noCarrinho: 5, emProcessoDePagamento: 5, NosPedidos: 5, status: "Em Produção"},
        {nome: "Produto 20", id: Math.random(), preco: 5, quantidade: 3, descricao: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc tellus augue, imperdiet vitae risus in, laoreet efficitur neque. Integer finibus convallis metus, non feugiat lorem posuere a.", noCarrinho: 5, emProcessoDePagamento: 5, NosPedidos: 5, status: "Em Produção"},
        {nome: "Produto 21", id: Math.random(), preco: 3, quantidade: 5, descricao: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc tellus augue, imperdiet vitae risus in, laoreet efficitur neque. Integer finibus convallis metus, non feugiat lorem posuere a.", noCarrinho: 5, emProcessoDePagamento: 5, NosPedidos: 5, status: "Em Produção"},
        {nome: "Produto 22", id: Math.random(), preco: 4, quantidade: 4, descricao: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc tellus augue, imperdiet vitae risus in, laoreet efficitur neque. Integer finibus convallis metus, non feugiat lorem posuere a.", noCarrinho: 5, emProcessoDePagamento: 5, NosPedidos: 5, status: "Em Produção"},
        {nome: "Produto 23", id: Math.random(), preco: 5, quantidade: 3, descricao: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc tellus augue, imperdiet vitae risus in, laoreet efficitur neque. Integer finibus convallis metus, non feugiat lorem posuere a.", noCarrinho: 5, emProcessoDePagamento: 5, NosPedidos: 5, status: "Em Produção"},
        {nome: "Produto 24", id: Math.random(), preco: 3, quantidade: 5, descricao: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc tellus augue, imperdiet vitae risus in, laoreet efficitur neque. Integer finibus convallis metus, non feugiat lorem posuere a.", noCarrinho: 5, emProcessoDePagamento: 5, NosPedidos: 5, status: "Em Produção"},
        {nome: "Produto 25", id: Math.random(), preco: 4, quantidade: 4, descricao: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc tellus augue, imperdiet vitae risus in, laoreet efficitur neque. Integer finibus convallis metus, non feugiat lorem posuere a.", noCarrinho: 5, emProcessoDePagamento: 5, NosPedidos: 5, status: "Em Produção"},
    ]
}

export default INITIAL_STATE